# Roughly Based on: https://www.smarthomebeginner.com/docker-media-server-2022/
version: "3.9"

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

services:

  # Portainer - WebUI for Containers
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      <<: *default-tz-puid-pgid
    command: -H unix:///var/run/docker.sock # Use Docker Socket Proxy and comment this line out, for improved security.
    ports: # Comment out if using Nginx Proxy Manager to access portainer WebUI.
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Use Docker Socket Proxy and comment this line out, for improved security.
      - $DOCKERDIR/appdata/portainer/data:/data # Change to local directory if you want to save/transfer config locally.


  # Downloads files and puts them in $DATADIR/downloads
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      <<: *default-tz-puid-pgid
      WEBUI_PORT: 8080
    volumes:
      - $DOCKERDIR/appdata/config:/config
      # - $DATADIR/downloads:/downloads
      - $DATADIR/downloads:/data/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  # Sonarr - TV Shows management
  # Tells qbittorrent what to download and keeps scanning $DATADIR/downloads,
  # once it is available, moves it to $DATADIR/media/tvseries
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      <<: *default-tz-puid-pgid
    ports:
      - "8989:8989"
    volumes:
      - $DOCKERDIR/appdata/sonarr:/config
      - $DATADIR/downloads:/data/downloads
      - $DATADIR/media:/data/media
      - "/etc/localtime:/etc/localtime:ro"

  # Sonarr - Movies
  # Tells qbittorrent what to download and keeps scanning $DATADIR/downloads,
  # once it is available, moves it to $DATADIR/media/moveis
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      <<: *default-tz-puid-pgid
    ports:
      - "7878:7878"
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      - $DATADIR/downloads:/data/downloads
      - $DATADIR/media:/data/media
      - "/etc/localtime:/etc/localtime:ro"

  # Helps sonarr to find torrents and pass it to qbittorrent via
  # $DOCKERDIR/appdata/config folder
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DOCKERDIR/appdata/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  # Reads data placed in $DATADIR/media and allows us to watch it on TV
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      <<: *default-tz-puid-pgid
      VERSION: 'docker'
    network_mode: host
    volumes:
      - $DOCKERDIR/appdata/config:/config
      - $DATADIR/media/tvseries:/tv
      - $DATADIR/media/movies:/movies
    restart: unless-stopped
